[package]
name = "decode_411"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }

[profile.release]
lto = "fat"
opt-level = "z"
strip = true
panic = "abort"
codegen-units = 1

[features]
fixed = []
