[package]
name = "mavica_411"
description = "Decode Sony Mavica .411 thumbnail images."
version.workspace = true
authors.workspace = true
license.workspace = true
edition = "2024"

[features]
fixed = []
